"""
Plot embeddings in 3D using plotly. Loads data generated by src/preprocess_data.py
"""

from pathlib import Path
import pandas as pd
import argparse

import sys
sys.path.append(str(Path(__file__).parents[1] / "TextSpace")) 
from plot3D import plot_embeddings_3d
from data import TextSpaceData

def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("--csv_file", type = str, default="plotly_data.csv")
    parser.add_argument("--embedding_type", type = str, default="emotion")

    return parser.parse_args()


def main():
    path = Path(__file__)
    args = parse_args()

    savepath = path.parents[1] / "fig"

    # load data
    data = pd.read_csv(path.parents[1] / "data" / args.csv_file)

    # create TextSpaceData object
    TextSpace = TextSpaceData(data, embedding_type=args.embedding_type)

    # plot embeddings in 3D
    fig = plot_embeddings_3d(TextSpace)

    fig.write_html(savepath / f"plotly_{args.embedding_type}.html")

if __name__ == "__main__":
    main()
